### ISSUE TITLE
postText.setBackground(null); caused java.lang.NoSuchMethodError error.

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr-android#184]
I believe this is an issue where we are trying to do something that is not supported by the API version on the phone.

```
java.lang.NoSuchMethodError: android.widget.EditText.setBackground
    at yellr.net.yellr_android.fragments.PostFragment.onCreateView(PostFragment.java:151)
    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:548)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1133)
    at android.app.Activity.performStart(Activity.java:4475)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1982)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2043)
    at android.app.ActivityThread.access$600(ActivityThread.java:124)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1149)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4502)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:812)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:579)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by thequbit** [comment]
This needs to be resolved for 0.1.8.
